version: '2'

services:

    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes: 
            - ./db/data:/db
        environment: 
            PGDATA: /db
        ports:
            - "5432:5432"